json.(card, :id, :title, :user_id, :board_id, :board_id, :user_id, :description, :created_at, :updated_at)
json.set!(:image_large, card.image.url(:large))
json.set!(:image_thumb, card.image.url(:thumb))
json.set!(:board_title, card.board.title)
json.set!(:user_username, card.user.username)
json.set!(:likes_card, current_user.likes_card?(card))
json.set!(:board_avatar, card.board.avatar(:thumb))
json.set!(:user_avatar, card.user.avatar(:thumb))