# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "Luke", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/luke.png"))
User.create(username: "Vader", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/vader.jpeg"))
User.create(username: "Leia", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/leia.jpg"))
User.create(username: "Han", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/han.jpg"))
User.create(username: "Obi Wan", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/obi_wan.jpg"))
User.create(username: "Lando", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/lando.jpg"))
User.create(username: "Emperor", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/emperor.jpeg"))
User.create(username: "Yoda", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/yoda.png"))
User.create(username: "Boba Fett", password: '123456', avatar: File.new("#{Rails.root}/seeds/images/boba_fett.jpg"))

luke = User.find_by_username("Luke")
vader = User.find_by_username("Vader")
leia = User.find_by_username("Leia")
han = User.find_by_username("Han")
obi_wan = User.find_by_username("Obi Wan")
lando = User.find_by_username("Lando")
emperor = User.find_by_username("Emperor")
yoda = User.find_by_username("Yoda")
boba_fett = User.find_by_username("Boba Fett")

Board.create(user_id: luke.id, public: true, title: "Tatooine", description: "Memories of home...", avatar: File.new("#{Rails.root}/seeds/images/tatooine.jpg"))
Board.create(user_id: vader.id, public: true, title: "Death Star", description: "The ability to destroy a planet is insignificant next to the power of the Force.", avatar: File.new("#{Rails.root}/seeds/images/death_star.png"))
Board.create(user_id: leia.id, public: true, title: "Rebel Alliance", description: "Down with the Empire", avatar: File.new("#{Rails.root}/seeds/images/rebel.svg"))
Board.create(user_id: emperor.id, public: true, title: "Empire", description: "Everything that has transpired has done so according to my design.", avatar: File.new("#{Rails.root}/seeds/images/empire.svg"))
Board.create(user_id: han.id, public: true, title: "Millenium Falcon", description: "It's the ship that made the Kessel Run in less than twelve parsecs.", avatar: File.new("#{Rails.root}/seeds/images/falcon.jpg"))
Board.create(user_id: obi_wan.id, public: true, title: "Light Side", description: "Use the Force, Luke.", avatar: File.new("#{Rails.root}/seeds/images/light_side.png"))
Board.create(user_id: lando.id, public: true, title: "Cloud City", description: "You truly belong here with us among the clouds", avatar: File.new("#{Rails.root}/seeds/images/cloud_city.jpg"))
Board.create(user_id: emperor.id, public: true, title: "Dark Side", description: "It is unavoidable. It is your destiny.", avatar: File.new("#{Rails.root}/seeds/images/dark_side.png"))
Board.create(user_id: yoda.id, public: true, title: "Dagobah", description: "Mudhole? Slimy? My home this is!", avatar: File.new("#{Rails.root}/seeds/images/dagobah.jpg"))

tatooine = Board.find_by_title("Tatooine")
death_star = Board.find_by_title("Death Star")
rebel_alliance = Board.find_by_title("Rebel Alliance")
empire = Board.find_by_title("Empire")
millenium_falcon = Board.find_by_title("Millenium Falcon")
light_side = Board.find_by_title("Light Side")
cloud_city = Board.find_by_title("Cloud City")
dark_side = Board.find_by_title("Dark Side")
dagobah = Board.find_by_title("Dagobah")

BoardLike.create(user_id: luke.id, board_id: tatooine.id)
BoardLike.create(user_id: luke.id, board_id: rebel_alliance.id)
BoardLike.create(user_id: luke.id, board_id: millenium_falcon.id)
BoardLike.create(user_id: luke.id, board_id: light_side.id)
BoardLike.create(user_id: luke.id, board_id: dagobah.id)
BoardLike.create(user_id: vader.id, board_id: death_star.id)
BoardLike.create(user_id: vader.id, board_id: empire.id)
BoardLike.create(user_id: vader.id, board_id: dark_side.id)
BoardLike.create(user_id: leia.id, board_id: rebel_alliance.id)
BoardLike.create(user_id: leia.id, board_id: light_side.id)
BoardLike.create(user_id: han.id, board_id: rebel_alliance.id)
BoardLike.create(user_id: han.id, board_id: millenium_falcon.id)
BoardLike.create(user_id: han.id, board_id: cloud_city.id)
BoardLike.create(user_id: obi_wan.id, board_id: tatooine.id)
BoardLike.create(user_id: obi_wan.id, board_id: rebel_alliance.id)
BoardLike.create(user_id: obi_wan.id, board_id: light_side.id)
BoardLike.create(user_id: obi_wan.id, board_id: dagobah.id)
BoardLike.create(user_id: lando.id, board_id: millenium_falcon.id)
BoardLike.create(user_id: lando.id, board_id: cloud_city.id)
BoardLike.create(user_id: emperor.id, board_id: death_star.id)
BoardLike.create(user_id: emperor.id, board_id: empire.id)
BoardLike.create(user_id: emperor.id, board_id: dark_side.id)
BoardLike.create(user_id: yoda.id, board_id: rebel_alliance.id)
BoardLike.create(user_id: yoda.id, board_id: light_side.id)
BoardLike.create(user_id: yoda.id, board_id: dagobah.id)
BoardLike.create(user_id: boba_fett.id, board_id: tatooine.id)
BoardLike.create(user_id: boba_fett.id, board_id: empire.id)
BoardLike.create(user_id: boba_fett.id, board_id: dark_side.id)

Friendship.create(user_id: luke.id, friend_id: leia.id)
Friendship.create(user_id: leia.id, friend_id: luke.id)
Friendship.create(user_id: luke.id, friend_id: han.id)
Friendship.create(user_id: han.id, friend_id: luke.id)
Friendship.create(user_id: luke.id, friend_id: obi_wan.id)
Friendship.create(user_id: obi_wan.id, friend_id: luke.id)
Friendship.create(user_id: obi_wan.id, friend_id: yoda.id)
Friendship.create(user_id: yoda.id, friend_id: obi_wan.id)
Friendship.create(user_id: luke.id, friend_id: lando.id)
Friendship.create(user_id: lando.id, friend_id: luke.id)
Friendship.create(user_id: luke.id, friend_id: yoda.id)
Friendship.create(user_id: yoda.id, friend_id: luke.id)
Friendship.create(user_id: han.id, friend_id: leia.id)
Friendship.create(user_id: leia.id, friend_id: han.id)
Friendship.create(user_id: han.id, friend_id: lando.id)
Friendship.create(user_id: lando.id, friend_id: han.id)
Friendship.create(user_id: leia.id, friend_id: obi_wan.id)
Friendship.create(user_id: obi_wan.id, friend_id: leia.id)
Friendship.create(user_id: leia.id, friend_id: lando.id)
Friendship.create(user_id: lando.id, friend_id: leia.id)
Friendship.create(user_id: vader.id, friend_id: emperor.id)
Friendship.create(user_id: emperor.id, friend_id: vader.id)
Friendship.create(user_id: vader.id, friend_id: boba_fett.id)
Friendship.create(user_id: boba_fett.id, friend_id: vader.id)
Friendship.create(user_id: emperor.id, friend_id: boba_fett.id)
Friendship.create(user_id: boba_fett.id, friend_id: emperor.id)

# Card.create(user_id:, board_id:, title:, description:, image:)
